name: Deployment pipeline

on:
  push:
    branches:
      - master
jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint

